Resources:
  RocketFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Rocket
      Handler: unused
      Runtime: provided
      MemorySize: 512
      CodeUri: .
      Events:
        api:
          Type: Api
          Properties:
            Path: /{all+}
            Method: any
    Metadata:
      BuildMethod: makefile
